python script_training.py \
    --ModelName MemAE \
    --ModelSetting Conv3DSpar \
    --Dataset Cataract \
    --MemDim 2000 \
    --EntropyLossWeight 0.0002 \
    --ShrinkThres 0.0025 \
    --BatchSize 10 \
    --Seed 1 \
    --SaveCheckInterval 1 \
    --IsTbLog True \
    --IsDeter True \
    --DataRoot /local/scratch/Cataract-1K-Full-Videos/ \
    --ModelRoot ./results/ \
    --Suffix Non